@startuml whitebox-1

skinparam shadowing false
scale 1200 width

actor "Bank Admin" as badmin
actor "TPP Developer" as tppd

package psd2-accelerator {
  file config

  [ssl-proxy] <<infrastructure>>

  badmin -> [config]
  [ssl-proxy] -> config

  package sandbox {

    [ssl-proxy] -> () api

    [xs2a] --> [testdata]
    [xs2a] -> [config]

    tppd --> [ssl-proxy]

    () api -- [xs2a]
    api -[hidden] [certificate-generator]
    api -[hidden] [developer-portal]

    tppd --> [developer-portal]
    tppd --> [certificate-generator]
  }

}

@enduml
