[[section-deployment-view]]


== Deployment View

=== adorsys Sample Setup

.deployment-view
image::deployment-view.svg[Deployment View, 100%, align="center"]

The PSD2 Accelerator consists of two deployments. The _sandbox_ itself provides the XS2A API and a web application (and its API) for the developer portal. These two components are provided by a single fat JAR but served on different ports. XS2A is hosted on port `:8080` and the _developer portal_ is hosted on port `:8081` (both configurable). XS2A needs access to a database to persist the Consent Management state. The configuration for the _sandbox_ is completely externalized (see <<Configuration>>).

---

The _ssl-proxy_ deployment is responsible for <<SSL Client Authentication>> required by XS2A. It forwards the certificate body to the _sandbox_ in an HTTP header (`tpp-qwac-certificate`). So SSL termination has to happen here, at least for the XS2A API part. The _ssl-proxy_ only validates the SSL client certificate because certain parts of the API are accessible without authentication (e.g. the Swagger file and Swagger UI). +
The _sandbox_ acts as a Certificate Authority (CA) and provides SSL Client Certificates to the TPP developers. The _ssl-proxy_ needs access to the _sandbox_ CA certificate in order to verify the TPP SSL client certificates (see <<Configuration>>).

_ssl_proxy_ listens on `:8443` (actual reverse proxy) and `:8090` (health check).

WARNING: The supplied _ssl-proxy_ is only meant to be used in development and must be substituted by an equivalent infrastructure component in prod (see <<Deploy on Your Own Infrastructure>>).

In our own setup on OpenShift both components of the _sandbox_ are available on different subdomains. The OpenShift loadbalancer terminates SSL for the _developer portal_ and does SSL passthrough for the _XS2A_ API so that the _ssl-proxy_ can terminate SSL itself.

NOTE: In reality all (SSL) traffic get passed through the Load Balancer to the _ssl-proxy_. The _ssl-proxy_ then does SSL termination *for both endpoints*  but SSL client authentication only for the XS2A API. We need this so we can start the exact same setup as on OpenShift with docker-compose for local development. _This is not a good idea for production._

=== Release Artifacts

We use https://github.com/adorsys/psd2-accelerator/releases[GitHub Releases] to publish our release notes, the Sandbox JAR and its SHA1 checksum.

Docker Images are released to https://hub.docker.com/u/adorsys[adorsys DockerHub account].

[options="header"]
|=======
| Artifact  | Image Name
| sandbox   | adorsys/psd2-sandbox:{acc-version}
| ssl-proxy | adorsys/psd2-sandbox-ssl-proxy:{acc-version}
|=======

[subs=attributes+]
[source,shell]
----
$ docker run -it --rm -v $PWD:/target adorsys/psd2-sandbox:{acc-version} sh -c "cp /opt/app-root/src/*.jar /target"
----

To build your own Docker images get the JAR from our image or use Docker Multi Stage Builds:

[subs=attributes+]
[source,Dockerfile]
----
FROM openjdk:8

COPY --from=adorsys/psd2-sandbox:{acc-version} /opt/app-root/src/sandbox-{acc-version}.jar .

CMD java -jar sandbox-{acc-version}.jar
----

=== Configuration

Configuration is done via https://docs.spring.io/spring-boot/docs/1.5.18.RELEASE/reference/htmlsingle/#boot-features-external-config[Spring Boot Externalized Configuration] and can be set via CLI arg, system property or environment variable. Since we intensively use Docker in our setup and environment variables are the idiomatic approach to configuration there, we stick to environment variables in the examples.

NOTE: Spring Boot automatically translates properties to environment variables. The environment variable `SPRING_DATASOURCE_URL` sets the property `spring.datasource.url`. Consult the https://docs.spring.io/spring-boot/docs/1.5.18.RELEASE/reference/htmlsingle/#boot-features-external-config-application-property-files[Spring Boot documentation] for more information.

==== sandbox

.Required Properties for sandbox
[[propertyTable]]
[options="header"]
|=======
| Property                   | Description        | Default
| BANK_PROFILE_PATH
a| File path to the customized `bank_profile.yml`.

Possible values could be `bank_profile.yml` (relative) or `/mnt/my_bank_profile.yml`

This is the actual business configuration reflecting the PSD2 features your bank offers. You can find the relevant documentation for this file at the https://github.com/adorsys/xs2a/blob/1.11/aspsp-profile/README.md[XS2A GitHub Project].

For an example and the actual default values used in the sandbox see the <<sample-bank-profile>> below.

| Points to the default `bank_profile.yml` YML embedded in the application
| SANDBOX_TESTDATA_TRANSACTIONS_PATH | Path and filename of the custom transaction data | Points to the default `transactions_dump.csv` CSV embedded in the application
| CERTIFICATE_FILTER
a| Set to the format of the QWAC certificate in the `tpp-qwac-certificate` header. This value depends on your SSL-Proxy configuration. Possible values are:

- _default_ for https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail[PEM] format without line breaks. Also known as "base64" format of the certificate.
- _tab_ for https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail[PEM] format with tabs (`\t`) instead of line breaks
- _mock_ disables the QWAC authentication and uses a hard coded test certificate instead (*do not use in prod!*)

| _tab_
| SANDBOX_FEATURE_UI_ENABLED                     | Enables/Disables the Sandbox UI.

 Possible values are: _true_ or _false_                   | _true_
| SPRING_DATASOURCE_PASSWORD                     | DB password                         | _(not set)_
| SPRING_DATASOURCE_URL                          | JDBC URL                            | _(not set)_
| SPRING_DATASOURCE_USERNAME                     | DB username                         | _(not set)_
| SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
| DB schema name (depends on used DB and configuration)
| _(not set)_
|=======

[[sample-bank-profile]]
.Sample bank_profile.yml
[source,yaml]
----
include::../../service/src/main/resources/bank_profile.yml[]
----

===== Customizing the Test Data

The IBANs of the different PSUs we provide are configurable. There is a default configuration in place which uses a made up routing number (**DE**XX**76036568**XXXXXXXXXX).

.Default Test Data Configuration
[source,yaml]
----
include::../../service/src/main/resources/testdata.yml[]
----

Every PSU has one or more accounts. The account order _does_ matter (e.g. the first IBAN of _PSU-Successful_ is always picked for the giro account). You can override the configuration by placing an edited copy in `$CWD/config` next to the JAR.

WARNING: Make sure that every IBAN you use is valid. We do not check externally set IBANs for correctness. If you use invalid IBANs, you might encounter problems when interacting with the XS2A API or with external systems. If a PSU has more than one IBAN, you need to supply all of them or the application won't start. To help with configuration and debugging, the effective `TestDataConfiguration` is logged (`INFO`) to the console at startup.

Besides the IBANs it is also possible to import transaction data using a CSV file (see <<propertyTable>>). The data will then replace the transactions of the giro account of the `PSU_Successful`.

The format of the CSV file must match the following example:

.Default Transaction Data
[source,csv]
----
include::../../service/src/main/resources/transactions_dump.csv[]
----

The CSV must comply with the following restrictions:

- The columns must be separated by `|`
- A header line is mandatory and must match the example
- Dates must be in the ISO format (YYYY-MM-DD)
- Payment amounts must use `.` instead of `,` as floating point separator


See <<Configuration>> for more information about the Spring Boot configuration mechanism.

==== ssl-proxy

.Required Properties for ssl-proxy
[options="header"]
|=======
| Property  | Description | Default
| API_INTERNAL_URL    | Internal URL where the _XS2A API_ is reachable (set in docker-compose) | `http://service:8080`
| API_EXTERNAL_URL    | External URL where the _XS2A API_ is reachable (set in docker-compose) | `api.psd2-accelerator.vcap.me`
| PORTAL_INTERNAL_URL | Internal URL where the _developer portal_ is reachable (set in docker-compose)  | `http://service:8081`
| PORTAL_EXTERNAL_URL | External URL where the _developer portal_ is reachable (set in docker-compose)  | `portal.psd2-accelerator.vcap.me`
|=======

.Required Files for ssl-proxy
[options="header"]
|=======
| File                        | Description                     | Default
| /opt/app-root/etc/nginx.pem | SSL Certificate                 | self signed one from adorsys
| /opt/app-root/etc/nginx.key | PK to SSL Certificate           | random PK for the self signed certificate
| /opt/app-root/etc/ca.crt    | PSD2 Accelerator CA Certificate | default adorsys CA certificate
|=======

NOTE: The PSD2 Accelerator CA certificate (ca.crt) is already embedded in the _ssl-proxy_. If you supply your own instance of this component you need to configure the proper SSL and CA certificates there. You can get the PSD2 Accelerator CA certificate by extracting it from the _ssl-proxy_ image. See <<Deploy on Your Own Infrastructure>> for more details.

==== Logging

We use the default https://docs.spring.io/spring-boot/docs/1.5.18.RELEASE/reference/html/howto-logging.html[Spring Boot logging configuration] and log everything to stdout.

The default log level is `INFO`. Set a different level with `LOGGING_LEVEL_ROOT=WARN` (global) or with `LOGGING_LEVEL_de.adorsys.psd2=WARN` (for everything below `de.adorsys.psd2`; please note the casing).

=== Deploy on Your Own Infrastructure

The PSD2 Accelerator deployment is quite flexible. The only required component is the _sandbox_ and its DB.

While we release Docker images only, the _sandbox_ can be run on any machine providing a recent JDK 8 (see <<Technology Requirements>>). See <<Release Artifacts>> to find out how to get the JAR.

WARNING: As of now we release Docker Images with a Spring Boot fat JAR with an embedded Tomcat only. We do not release the _sandbox_ as a WAR (yet).

The _ssl-proxy_ can (and should) be substituted by existing infrastructure. There are many options which components can replace our _ssl-proxy_. Most likely it's going to be some kind of load balancer in hardware (F5) or software (HAProxy, some API Gateway). It's only purpose is SSL Client Authentication and forwarding the SSL Client Certificate (QWAC) in PEM format (single line or tab delimited, see <<Configuration>>) in an HTTP header named `tpp-qwac-certificate` to the _sandbox_ (see <<adorsys Sample Setup>>).

The connection between _sandbox_ and any SSL-Proxy is made on the SSL-Proxy side with custom configuration. The only information that comes from the _sandbox_ is the Sandbox CA Certificate (ca.crt). You will need to make this file accessible to your SSL-Proxy.

[subs=attributes+]
[source,shell]
----
# copy ca.crt from the image to the current directory
$ docker run -it --rm -v $PWD:/target adorsys/psd2-sandbox-ssl-proxy:{acc-version} sh -c "cp /opt/app-root/etc/ca.crt /target"
----

See <<NGINX SSL Configuration>> for an actual sample of our NGINX configuration.

==== Technical Requirements / Sizing

- the _sandbox_ needs a recent JDK 8 (if you aren't using the Docker Image)
- HA setup is possible
  - all state is shared in the DB
  - zero downtime deployments are **not** guaranteed (see the note about <<downtime_db_migration, DB migrations>>)
  - DB availability depends on your setup
- supported databases (see <<Use Your Own Database>>):
  ** PostgreSQL 9+
  ** Oracle 11g+
  ** MariaDB 10+
- 2-4 GiB RAM per _sandbox_ deployment is a good starting point for prod *(monitor this!)*
- _ssl-proxy_ needs 128 - 512 MiB RAM *(don't use in prod!)*
- the DB schema needs enough disk space because consents are persisted here (grows over time) *(monitor this!)*

==== Production Ready Features

===== Health Checks

There are health check endpoints for both deployments. They return `200 OK` when healthy.

- `GET http://sandbox:8081/management/health`
- `GET http://sandbox:8080/management/health`
- `GET http://ssl-proxy:8090/healthz`

===== Using the Actuator Features

We use Spring Boot Actuator for metrics, health checks and information about the deployment. Per default there are three endpoints enabled (active on both ports).

- `GET /management/health` returns `{status: "UP"}` if we're good
- `GET /management/info` returns information about
    ** deployed version
    ** git commit/tag from which it was build
    ** bundled XS2A impl and spec version
- `GET /management/metrics` returns the default https://docs.spring.io/spring-boot/docs/1.5.18.RELEASE/reference/html/production-ready-metrics.html[Spring Actuator Metrics]

NOTE: The actuator endpoints are all public. We do not expect any sensitive information there. Please verify this.

If you want to disable certain endpoints you can do so:

[source]
----
endpoints.metrics.enabled=false
endpoints.health.enabled=false
endpoints.info.enabled=false
----

WARNING: (KNOWN BUG) You can't disable the endpoints with CLI arguments. System properties and environment variables work fine, though.

Disable all production ready features by not exposing `/management/**` to the public.

==== Use Your Own Database

We bundle a recent PostgreSQL JDBC driver in the _sandbox_ JAR. For other databases you need to supply the correct JDBC driver. We use Springs https://docs.spring.io/spring-boot/docs/1.5.17.RELEASE/reference/html/executable-jar.html#executable-jar-property-launcher-features[PropertiesLauncher] to allow adding JARs to the classpath. The default `CMD` in our Dockerfile adds the folder `/opt/app-root/src/lib` per default. Put your JDBC driver there so it gets loaded on application start:

[subs=attributes+]
[source,shell]
----
$ docker run -it --rm -v $PWD/ojdbc8.jar:/opt/app-root/src/lib adorsys/psd2-sandbox:{acc-version}
----

If you run the _sandbox_ without Docker, you need to set `loader.path` yourself:

[subs=attributes+]
[source,shell]
----
$ ls lib
ojdbc8.jar
# adds all JARs in "./lib" to the classpath
$ java -jar -Dloader.path="lib" sandbox-{acc-version}.jar
----

Only databases listed in <<Technical Requirements / Sizing>> are supported. The Liquibase migration may fail with others.

WARNING: Please make sure to set the right `SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA` depending on your setup.

==== Database Migration

There are three options to do database migration.

[[downtime_db_migration]]
[WARNING]
====
- every approach needs at least read access to the DB
- you should scale down the deployment while migrating or requests may fail
====

===== Automatically with Liquibase

Set the configuration property `liquibase.enabled=true` and migration will be run automatically with the configured connection details.

===== Manually with Liquibase

The `sandbox-{acc-version}.jar` can be used as CLI application to do the migration with different credentials than the actual deployment.

[subs=attributes+,source,shell]
----
$ java -jar sandbox-{acc-version}.jar migrate --spring.datasource.url=$JDBC_URL --spring.datasource.username=$USR --spring.datasource.password=$PASS
----

===== Manually with self-generated SQL schema

The CLI can echo the full schema instead of doing the actual migration, too. This command creates a file `database-migration.sql` which contains the SQL that Liquibase would run to update the schema.

[subs=attributes+,source,shell]
----
$ java -jar sandbox-{acc-version}.jar create-schema --spring.datasource.url=$JDBC_URL --spring.datasource.username=$USR --spring.datasource.password=$PASS
----

=== Reset Sandbox Data
In a sandbox environment it is good practice to reset the data periodically to the factory-defaults. To reset the data of the PSD2 Accelerator, the following steps are needed:

 . Stop the running PSD2 Accelerator process by terminating the jar or by stopping the docker container.
 . Delete the database data by redeploying your database instance. The procedure of resetting the database depends on your local deployment setup. Check the documentation of your preferred database for further information.
 . Restart the PSD2 Accelerator.

=== Build Pipeline

NOTE: This is no longer accurate. +
TODO: document build with Travis CI when done.

We use https://github.com/adorsys/psd2-accelerator/pipelines[GitLab CI] for the pipeline. Build, release, testing, Code coverage, linting and compilation/deployment of this architecture documentation are automated. Every artifact we build is also kept for one week and can be downloaded in corresponding pipeline/job.

Every commit on master pushes images for _sandbox_ and _ssl-proxy_ to the adorsys OpenShift. An image change trigger then starts a new deployment. The arc42 documentation is also built on every commit and published with the http://adorsys.github.io/psd2-accelerator[GitHub Pages] feature.

Each tag which follows the semver pattern with a leading `v` like `v1.0.0` results in a tagged release. Tags are pushed to https://hub.docker.com/u/adorsys/[DockerHub] (see <<Release Artifacts>>). Releases are created locally with our `infrastructure/build/release.sh` script.

=== Deployment Samples

==== docker-compose

This docker-compose setup will start the _sandbox_ on port `:8080`/`:8081` and the _ssl-proxy_ on port `:8443`. The _ssl-proxy_ knows how to serve the domains https://portal.psd2-accelerator.vcap.me and https://api.psd2-accelerator.vcap.me locally with a self signed SSL certificate.

.docker-compose.yml
[source,yaml]
----
include::../../docker-compose.yml[]
----

==== OpenShift Deployment Config

This is an excerpt of the adorsys OpenShift deployment on https://sandbox-api.dev.adorsys.de and https://sandbox-portal.dev.adorsys.de. The PostgreSQL deployment we use is not shown here.

.sandbox-dc.yml
[source,yaml]
----
include::../../infrastructure/openshift/sandbox-dc.yml[]
----

.sandbox-svc.yml
[source,yaml]
----
include::../../infrastructure/openshift/sandbox-svc.yml[]
----

.sandbox-route-api.yml
[source,yaml]
----
include::../../infrastructure/openshift/sandbox-route-api.yml[]
----

.sandbox-route-portal.yml
[source,yaml]
----
include::../../infrastructure/openshift/sandbox-route-portal.yml[]
----

==== NGINX SSL Configuration

.Relevant Samples of our NGINX SSL Configuration
[source]
----
# sandbox-xs2a-server.conf
include::../../ssl-proxy/root/opt/app-root/etc/nginx.d/sandbox-xs2a-server.conf[]
----

[source]
----
# sandbox-portal-server.conf
include::../../ssl-proxy/root/opt/app-root/etc/nginx.d/sandbox-portal-server.conf[]
----
