[[section-design-decisions]]
== Design Decisions

Modular Monolith/Well Designed Monolith::
+
We start with a monolithic approach to keep it simple. Unrelated Use-Cases are represented by top-level packages
in the backend or Angular modules in the frontend. We don't allow dependencies between unrelated
features. These features are also transaction boundaries. We might enforce these rules at build time with tools like https://github.com/TNG/ArchUnit[ArchUnit] if we see that design problems are introduced despite our code-reviews and
guidelines.
+
This approach allows us to scale out later if we need it, while keeping development and deployment as simple as possible.
+
See also:

* https://martinfowler.com/bliki/MonolithFirst.html
* https://www.youtube.com/watch?v=kbKxmEeuvc4
* https://scs-architecture.org/

Stick to a Tech-Stack Commonly Found in Banks::
We try to be conservative in our tech choice. To reduce friction we use technologies that our potential
customers know and can handle.
+
Right now we use:

* Java 8 / Spring Boot 1 (XS2A forces us to use these versions, too)
* Angular 7
* Postgres 10
* Docker (optional)

Deployment as a single JAR::
To make local development and deployment easy, we try to bundle everything in the _sandbox_ JAR:
* _profile_ is embedded instead of being deployed stand-alone
* _consent-management_ is embedded instead of being deployed stand-alone
* the ui is a separate top-level Angular project but is embedded in the resulting JAR as static content

Different Spring Contexts for XS2A and the Sandbox::
Our JAR hosts two Spring Web Applications on different ports. The XS2A context is isolated from the Sandbox context.
This allows us to:
* import the original XS2A configuration without affecting the Sandbox
* host both applications on different subdomains
* use two different but simpler Spring Security configurations instead of a complicated one

Monorepo::
All our code lives in a single https://github.com/adorsys/psd2-accelerator[PSD2 Accelerator repository]. Every
project / artifact gets a top-level directory (service, ui, arc42, deployment configuration). This
allows us to
* reflect our architecture in the repo
* build and version everything together and at once
* get started quickly (easy discovery and build)
